# Generated by Django 6.1.1 on 2026-10-05 12:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=90)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=70, unique=True)),
                ('abbreviation', models.CharField(max_length=2, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=170)),
                ('address_line', models.CharField(blank=True, max_length=200)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_telehealth', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinics', to='directory.city')),
                ('treatments', models.ManyToManyField(blank=True, related_name='clinics', to='catalog.treatment')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClinicPeptide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price_note', models.CharField(blank=True, max_length=120)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='directory.clinic')),
                ('peptide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='catalog.peptide')),
            ],
        ),
        migrations.AddField(
            model_name='clinic',
            name='peptides',
            field=models.ManyToManyField(blank=True, related_name='clinics', through='directory.ClinicPeptide', to='catalog.peptide'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_name', models.CharField(max_length=80)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, max_length=120)),
                ('body', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='directory.clinic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='directory.state'),
        ),
        migrations.AddConstraint(
            model_name='clinicpeptide',
            constraint=models.UniqueConstraint(fields=('clinic', 'peptide'), name='uniq_clinic_peptide'),
        ),
        migrations.AddIndex(
            model_name='clinic',
            index=models.Index(fields=['is_published', 'city'], name='clinic_published_city_idx'),
        ),
        migrations.AddConstraint(
            model_name='clinic',
            constraint=models.UniqueConstraint(fields=('city', 'slug'), name='uniq_clinic_slug_per_city'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('state', 'slug'), name='uniq_city_slug_per_state'),
        ),
    ]
