# Generated by Django 6.1.1 on 2026-10-05 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peptide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=130, unique=True)),
                ('regulatory_status', models.CharField(choices=[('fda_approved', 'FDA Approved'), ('compoundable', 'Compoundable'), ('research_use', 'Research Use')], db_index=True, max_length=20)),
                ('drug_class', models.BooleanField(default=False)),
                ('summary', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('is_popular', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.CharField(max_length=90, unique=True)),
                ('tagline', models.CharField(help_text='One-liner on the category card.', max_length=160)),
                ('tint', models.CharField(choices=[('mint', 'Mint'), ('peach', 'Peach'), ('rose', 'Rose'), ('lavender', 'Lavender'), ('sky', 'Sky')], default='mint', max_length=10)),
                ('sort_order', models.PositiveSmallIntegerField(max_length=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('summary', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('peptides', models.ManyToManyField(blank=True, related_name='protocols', to='catalog.peptide')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protocols', to='catalog.treatment')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='peptide',
            name='treaments',
            field=models.ManyToManyField(blank=True, related_name='peptides', to='catalog.treatment'),
        ),
    ]
