# Generated by Django 6.1.1 on 2026-10-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
