# Generated by Django 6.1.1 on 2026-10-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_treatment_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peptide',
            name='drug_class',
            field=models.BooleanField(max_length=120),
        ),
    ]
