# Generated by Django 6.1.1 on 2026-10-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_peptide_drug_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peptide',
            name='drug_class',
            field=models.CharField(max_length=120),
        ),
    ]
