# Generated by Django 6.1.1 on 2026-10-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_peptide_drug_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peptide',
            old_name='treaments',
            new_name='treatments',
        ),
    ]
